import type { Metadata } from "next";
import "../../globals.css";

export const metadata: Metadata = {
  title: "Our team",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element => {
  return (
    <html lang="en">
      {/* <Suspense fallback={<Loading/>}> */}

      <body suppressHydrationWarning={true}>{children}</body>
      {/* </Suspense> */}
    </html>
  );
};

export default RootLayout;
